version: "3"
services:
  db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    container_name: key-python-mission
    ports:
      - "8000:8000"
      - "3333:3333"
    volumes:
      - ./:/workspace
      - key-pythom-mission-extensions:/root/.vscode-server/extensions
      - key-pythom-mission-extensions-insiders:/root/.vscode-server-insiders/extensions
    depends_on:
      - db
    environment:
      DEBUG: "True"
      POSTGRES_NAME: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    tty: true

volumes:
  pgdata:
  key-pythom-mission-extensions:
  key-pythom-mission-extensions-insiders:
